In [ ]:
print(14,0,0,18,2,4,22,-3,9)
print(13,4.3333,2.0817,1.6667)
print(17.6667,2.6247)
print('yes')
print(2,20)

In [26]:
print(20.8,1.2,1.2,1.44,13,3,3,9,21,-3,3,9)
print(2.4,2.5456)
print(1.5)
print((3,2),(2,1),(3,1))

20.8 1.2 1.2 1.44 13 3 3 9 21 -3 3 9
2.4 2.5456
1.5
(3, 2) (2, 1) (3, 1)


In [ ]:
print(1,0.7311,1,0,-1,0.2689,0,0,2,0.8808,1,1)
print(4, 3, 1, 2, 0.7000, 0.8000, 0.6667, 0.7273)          
print("down", "recall") 

In [31]:
x1 = np.array([1,0.5,2])
x2 = np.array([0,1,1])
z = -1 + 2*x1 + (-1)*x2
p = np.round(1/(1+np.exp(-z)),4)
print(z)
print(p)

[ 1. -1.  2.]
[0.7311 0.2689 0.8808]


In [ ]:
a = [1,0,1,1,0,0,1,0,1,1]
b = [1,0,0,1,1,0,1,0,0,1] 
# Q03
print(1, 0.7311, 1, 0, -1, 0.2689, 0, 0, 2, 0.8808, 1, 1)   # 3a
print(4, 3, 1, 2, 0.7000, 0.8000, 0.6667, 0.7273)             # 3b
print("down", "recall")                                        # 3c

array([[3, 1],
       [2, 4]])

In [23]:
import numpy as np
x1 = np.array([10,4,8])
x2 = np.array([2,5,10])
y_t = np.array([22,16,18])
y = 5 + 1.5*x1 + 0.4*x2
print(y)
print('-----------------------')
print(y_t-y)
print('-----------------------')
print(abs(y_t-y))
print('-----------------------')
print((y_t-y)**2)
print('-----------------------')

[20.8 13.  21. ]
-----------------------
[ 1.2  3.  -3. ]
-----------------------
[1.2 3.  3. ]
-----------------------
[1.44 9.   9.  ]
-----------------------


In [25]:
from sklearn import metrics
print(round(metrics.mean_absolute_error(y_t,y),4))
print(round(metrics.root_mean_squared_error(y_t,y),4))


2.4
2.5456


In [ ]:
import numpy as np
x = np.array([2,4,6])
y_t = np.array([14,20,19])
y = 10 + 2*x
print(y)
print('-----------------------')
print(y_t-y)
print('-----------------------')
print((y_t-y)**2)
print('-----------------------')


[14 18 22]
-----------------------
[ 0  2 -3]
-----------------------
[0 4 9]


In [9]:
from sklearn import metrics
print(sum((y_t-y)**2))
print(round(metrics.mean_squared_error(y_t,y),4))
print(round(metrics.root_mean_squared_error(y_t,y),4))
print(round(metrics.mean_absolute_error(y_t,y),4))

13
4.3333
2.0817
1.6667


In [21]:
print(round(np.mean(y_t),4))
x = np.mean(y_t)
x = np.array([x,x,x])
print(round(metrics.root_mean_squared_error(y_t,x),4))

17.6667
2.6247


In [ ]:
print(2, 32, "C1", 5, 25, "C1", 128, 18, "C2", 130, 20, "C2", 5, 25, "C1") 
print(50)                                                                         
print(1.3333, 1.3333, 8.5000, 7.5000)                                             
print(2.3333, "yes")                                                              
print("yes")                                                                      

In [ ]:
print(0.5, 0.6, 0.6457, 1, 0.3543, -0.5, -0.4, 0.4013, 0, 0.4013, 0.5, -0.2, 0.4502, 0, 0.5498, -0.5, 0.3, 0.5744, 1, 0.5744)
print(0.4700, "yes")                                                                                                                
print("R3", "R4")                                                                                                                   
print(1.2)                                                                                                                          

In [36]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, root_mean_squared_error

# Load dataset
df = pd.read_csv("house_prices.csv")

# Target
y = df["price_lkr_mn"]

# Features
X = df[["size_sqft", "rooms", "age_years", "distance_km"]]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Fit Linear Regression
model = LinearRegression()
model.fit(X_train, y_train)

# a) Intercept and coefficients
print(round(model.intercept_,4),round(model.coef_[0],4),round(model.coef_[1],4),round(model.coef_[2],4),round(model.coef_[3],4))

# b) Predictions on test set
y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(round(mae,4),round(rmse,4),round(r2,4))

# c) Predict price for new house
new_house = pd.DataFrame({
    "size_sqft": [1800],
    "rooms": [3],
    "age_years": [12],
    "distance_km": [8]
})

predicted_price = model.predict(new_house)

print(round(predicted_price[0],4))

4.2382 0.012 1.4921 -0.0588 -0.2376
1.9272 2.3502 0.9436
27.6389


In [39]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

# Load dataset
df = pd.read_csv("customer_churn.csv")

# Target
y = df["churn"]

# Features
X = df.drop(columns=["churn"])

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    stratify=y,
    random_state=42
)

# a) Share of training set that churned
train_churn_share = y_train.mean()

print(round(train_churn_share,4))

# Standardization
scaler = StandardScaler()

X_train_s = scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)

# Logistic Regression
model = LogisticRegression(max_iter=1000)

model.fit(X_train_s, y_train)

# Predictions
y_pred = model.predict(X_test_s)

# b) Accuracy
accuracy = accuracy_score(y_test, y_pred)

print(round(accuracy,4))

# c) Precision, Recall and F1
precision = precision_score(y_test, y_pred, pos_label=1)
recall = recall_score(y_test, y_pred, pos_label=1)
f1 = f1_score(y_test, y_pred, pos_label=1)

print(round(precision,4),round(recall,4),round(f1,4))

# d) Confusion matrix
cm = confusion_matrix(y_test, y_pred)

TN, FP, FN, TP = cm.ravel()

print(round(TN,4),round(FP,4),round(FN,4),round(TP,4))

0.2983
0.76
0.62 0.5167 0.5636
121 19 29 31
