### <u>Cosine Similarity</u>

<table style='margin-right:auto;margin-left:auto'><td style="padding:20px;color:red">
cos(theeta) = <b>a.b/|a||b|</b></td>
</table>

In a movie recommendation system, a particular users' user preferance recorded as (3,3).<br>
<b>a.action preferance<br>b.comedy preferance<br></b>
Movie A can be represented as (6,4) based on other users ratings.Movie B can be represented as (1,7)<br>
based on other suers ratings.<br>
<b>I.Calculate the cosine similarity between the movie A and user preferance.<br></b>
<b>II.Calculate the cosine similarity between the movie B and the user preferance.<br></b>
<b>III.Based on the calculations,justify which movie is more prefered by the user.</b>

i. (3,3).(6,4)/3\*2\*root(26)=5/root(26)=0.98<br>
ii. (3,3).(1,7)/3\*5\*2=0.8<br>
iii. 0.98>0.8 => cos(alpha1)<cos(alpha2) => Movie A is preferred.

### ***Numpy Practising***

In [5]:
import numpy as np
array_01 = np.array([1,2,3,4])
print(array_01)
print(type(array_01))

[1 2 3 4]
<class 'numpy.ndarray'>


No need to add list inside np.array().We can add tuples also.

In [6]:
import numpy as np
array_01 = np.array((5,6,7,8))
print(array_01)
print(type(array_01))

[5 6 7 8]
<class 'numpy.ndarray'>


In [7]:
list_01 = [1,2,3,4]
list_02 = [5,6,7,8]
print(list_01+list_02)

[1, 2, 3, 4, 5, 6, 7, 8]


Numpy Arrays support vectorized operations.

In [ ]:
list_01 = [1,2,3,4]
list_02 = [5,6,7,8]
array_01 = np.array(list_01+list_02)
print(array_01)
#############################
array_01 = np.array(list_01)
array_02 = np.array(list_02)
print(array_01+array_02)
print(array_01-array_02)
print(array_01*array_02)
print(array_01/array_02)

[1 2 3 4 5 6 7 8]
[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


### Dot Product from Numpy Arrays

In [18]:
list_01 = [1,2,3,4]
list_02 = [5,6,7,8]
array_01 = np.array(list_01)
array_02 = np.array(list_02)
print(sum(array_01*array_02))
###########################################
print('-------------From function---------')
def calcualte_dot_product(vector_01,vector_02):
    if len(vector_01)!=len(vector_02):
        return f'Dimensions are different'
    return sum(vector_01*vector_02)
print(calcualte_dot_product(array_01,array_02))

70
-------------From function---------
70


### **2D Arrays in Numpy**

<img src='img1.jpeg'>

In [4]:
import numpy as np
array_01 = np.array([[6,8,10,12],[4,9,3,2],[10,12,15,17]])
print(array_01)
print(type(array_01))

[[ 6  8 10 12]
 [ 4  9  3  2]
 [10 12 15 17]]
<class 'numpy.ndarray'>


In [12]:
import numpy as np
array_01 = np.array([[6,8,10,12],[4,9,3,2],[10,12,15,17]])
print('No. of Elements in axis :',array_01.shape)
print('Dimension of the Array :',array_01.ndim)
print('No. of individula elements :',array_01.size)
print(len(array_01))

No. of Elements in axis : (3, 4)
Dimension of the Array : 2
No. of individula elements : 12
3


In [17]:
import numpy as np
array_01 = np.array([[[6,8,10,12],[4,9,3,2],[10,12,15,17]],[[6,8,1,1],[3,6,8,2],[9,7,1,4]]])
print('No. of Elements in axis :',array_01.shape)
print('Dimension of the Array :',array_01.ndim)
print('No. of individual elements :',array_01.size)
print(len(array_01))

No. of Elements in axis : (2, 3, 4)
Dimension of the Array : 3
No. of individual elements : 24
2


In [20]:
list_01 = [1,2,3,4]
array_01 = np.array(list_01,dtype=np.int16)
print(array_01.dtype)

int16


In [19]:
list_01 = [1.1,2,3,4]
array_01 = np.array(list_01)
print(array_01.dtype)

float64


When we use dtype float32 instead of float64 we cannot show more decimal places.So <b>accuracy</b> decreases.<br><br><br>
<img src='img2.jpeg'>

### Matrices

Define this matrix as 2D numpy array then show,<br>
I.Print the second raw.<br>
II.Print the third column.<br>
III.Print the elments from second raw.<br>
IV.Print the elements from second column to second raw.

In [3]:
import numpy as np
array_01 = np.array([[1,9,5,8],[4,5,3,6],[6,5,4,10]])
print(array_01[1])
print(array_01[0][2:3],array_01[1][2:3],array_01[2][2:3])
print(array_01[1],array_01[2])
print(array_01[0][1:],array_01[1][1:])


[4 5 3 6]
[5] [3] [4]
[4 5 3 6] [ 6  5  4 10]
[9 5 8] [5 3 6]


<b>Don't do like above.</b> 

In [12]:
import numpy as np
array_01 = np.array([[1,9,5,8],[4,5,3,6],[6,5,4,10]])
print(array_01[1])
print(array_01[:,2:3])
print(array_01[1:])
print(array_01[:2,1:])

[4 5 3 6]
[[5]
 [3]
 [4]]
[[ 4  5  3  6]
 [ 6  5  4 10]]
[[9 5 8]
 [5 3 6]]


## Matrix Scalar multiplication

In [13]:
import numpy as np
array_01 = np.array([[1,9,5,8],[4,5,3,6],[6,5,4,10]])
array_02 = 2*array_01
print(array_02)

[[ 2 18 10 16]
 [ 8 10  6 12]
 [12 10  8 20]]


## Array Multiplication

In [14]:
import numpy as np
array_01 = np.array([[1,9,5,8],[4,5,3,6],[6,5,4,10]])
array_02 = 2*array_01
print(array_01*array_02)

[[  2 162  50 128]
 [ 32  50  18  72]
 [ 72  50  32 200]]


## Matrix Multiplication

In [17]:
import numpy as np
array_01 = np.array([[1,9,5,8],[4,5,3,6],[6,5,4,10]])
array_02 = np.array([[1,9,5,8],[4,5,3,6],[6,5,4,10],[1,2,3,4]]) 
print(array_01 @ array_02)

[[ 75  95  76 144]
 [ 48  88  65 116]
 [ 60 119  91 158]]


In [18]:
import numpy as np
array_01 = np.array([[1,9,5,8],[4,5,3,6],[6,5,4,10]])
array_02 = np.array([[1,9,5,8],[4,5,3,6],[6,5,4,10],[1,2,3,4]]) 
print(np.matmul(array_01,array_02))

[[ 75  95  76 144]
 [ 48  88  65 116]
 [ 60 119  91 158]]


#### <b>Don't use the following for matrix Multiplication.</b>

In [19]:
import numpy as np
array_01 = np.array([[1,9,5,8],[4,5,3,6],[6,5,4,10]])
array_02 = np.array([[1,9,5,8],[4,5,3,6],[6,5,4,10],[1,2,3,4]]) 
print(np.dot(array_01,array_02))

[[ 75  95  76 144]
 [ 48  88  65 116]
 [ 60 119  91 158]]


### Matrix Transpose

In [20]:
import numpy as np
array_01 = np.array([[1,9,5,8],[4,5,3,6],[6,5,4,10]])
print(array_01.T)

[[ 1  4  6]
 [ 9  5  5]
 [ 5  3  4]
 [ 8  6 10]]
